import jsPDF from "jspdf";

interface PlaceholderTx {
  id: string;
  vendor_raw: string | null;
  vendor_normalized: string | null;
  amount: number | null;
  transaction_date: string | null;
  card_last_four: string | null;
  employeeName: string | null;
  periodName: string | null;
}

export async function buildPlaceholderBlob(tx: PlaceholderTx): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 50;
  const contentW = pageW - margin * 2;
  let y = 50;

  const vendor = tx.vendor_normalized ?? tx.vendor_raw ?? "—";
  const amount = tx.amount != null ? `$${Number(tx.amount).toFixed(2)}` : "—";
  const card = tx.card_last_four ? `•••• ${tx.card_last_four}` : "—";

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Southern Roof Consultants", margin, y);

  doc.setFontSize(22);
  doc.setTextColor(160, 160, 160);
  doc.text("RECEIPT PLACEHOLDER", pageW - margin, y, { align: "right" });
  doc.setTextColor(0, 0, 0);

  y += 16;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(1);
  doc.line(margin, y, pageW - margin, y);
  y += 28;

  // Notice box
  const noticeText =
    "This document is NOT an original receipt. It is a system-generated placeholder created by SpendSync to represent a credit card transaction for which no employee receipt was submitted. This document does not constitute proof of business purpose.";

  doc.setFillColor(255, 248, 230);
  doc.setDrawColor(220, 200, 150);
  doc.setLineWidth(0.75);
  const noticeLines = doc.splitTextToSize(noticeText, contentW - 24);
  const noticeH = noticeLines.length * 16 + 24;
  doc.roundedRect(margin, y, contentW, noticeH, 4, 4, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(140, 100, 20);
  doc.text("NOTICE", margin + 12, y + 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 60, 10);
  doc.text(noticeLines, margin + 12, y + 34);
  doc.setTextColor(0, 0, 0);

  y += noticeH + 30;

  // Transaction details table
  const rows: [string, string][] = [
    ["Vendor", vendor],
    ["Amount", amount],
    ["Transaction Date", tx.transaction_date ?? "—"],
    ["Card", card],
    ["Employee", tx.employeeName ?? "—"],
    ["Period", tx.periodName ?? "—"],
    ["Document Generated", new Date().toISOString()],
    ["Transaction ID", tx.id],
  ];

  const labelW = 150;
  const rowH = 26;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Transaction Details", margin, y);
  y += 18;

  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);

  rows.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(248, 248, 248);
      doc.rect(margin, y - 2, contentW, rowH, "F");
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(label, margin + 10, y + 14);

    const isId = label === "Transaction ID";
    doc.setFont(isId ? "courier" : "helvetica", "normal");
    doc.setFontSize(isId ? 8 : 10);
    doc.setTextColor(30, 30, 30);
    doc.text(value, margin + labelW, y + 14);

    y += rowH;
  });

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);

  // Footer
  y = doc.internal.pageSize.getHeight() - 50;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by SpendSync · Southern Roof Consultants · This placeholder is for internal reconciliation purposes only.",
    pageW / 2,
    y,
    { align: "center" }
  );

  return doc.output("blob");
}
